export const RoutesConfig = {
    LOGIN: 'Login',
    REGISTER: 'Register',
    ON_BOARDING: 'OnBoarding',
    FORGET: 'Forget',
    RESET_PASSWORD: 'ResetPassword',
    DASHBOARD: 'Dashhboard',
    HOME: 'Home',
    TRANSACTION: 'Transaction',
    SETTINGS: 'Settings',
    HELP: 'Help',
    DEPOSIT: 'Deposit',
    WITHDRAWAL: 'Withdrawal',
    SUCCESS_SCREEN: 'Success screen',
    SET_UP_YOUR_PROFILE: 'SetUpYourProfile',
    REALIDSCREEN: 'RealIDScreen',
    CARETOSHARESCREEN: 'CareToShareScreen',
    ALIASSCREEN: 'AliasScreen',
}